<script setup lang="ts">
import { computed, onMounted, onUnmounted, ref } from 'vue'
import { CalendarDays, MapPin } from '@lucide/vue'
import { EVENT } from '~/composables/useCountdown'

/**
 * Full-viewport hero built on a LIVE VECTOR SCENE (app/components/HeroScene.server.vue,
 * generated by remotion/scripts/build-scene.cjs).
 *
 * This replaced a 1.1MB AI-generated film, and with it went every line of
 * autoplay machinery: the deferred `src`, the play() retry loop, gesture
 * arming across five event types, the muted-as-property workaround, the
 * `ended`/`timeupdate` tail detection and the 520ms crossfade. None of it has
 * an equivalent here, because none of the problems it solved exist:
 *
 * - There is no download to defer. The scene arrives inside the SSR HTML, so
 *   there is no second network round-trip and no poster to stand in for one.
 * - There is no autoplay policy. CSS animation is not gated on user gestures,
 *   so it cannot be refused, and there is no rejected promise to recover from.
 * - There is no loop seam to hide. The old film's first and last frames were
 *   0.174 RMSE apart, which is what the crossfade concealed. Every animation
 *   here divides a 48s master cycle, so frame(0) and frame(48s) are the same
 *   image -- verified at 0.000 RMSE by remotion/scripts/verify-loop.cjs.
 *
 * The pause control was REMOVED at the owner's request. Two consequences worth
 * knowing, neither of them hidden:
 *
 * - WCAG 2.2.2 (Pause, Stop, Hide) asks for a mechanism to stop motion that
 *   starts on its own and runs past five seconds. There is now no in-page
 *   mechanism, so the remaining accommodation is `prefers-reduced-motion`,
 *   which switches every animation off at the OS level.
 * - Because nothing can stop it in-page, the motion is kept deliberately
 *   small: the camera push-in is composited (see hero-scene.css) and every
 *   other movement is a local, low-amplitude loop.
 */

/**
 * Save-Data, honoured on BOTH sides of hydration.
 *
 * The header is only readable on the server, so the decision is made there and
 * carried across in the payload via useState. Computing it in plain component
 * setup does NOT work: setup runs again in the browser, where
 * useRequestHeaders() returns {}, so the server's `true` silently became
 * `false` on the client and the animation started anyway -- defeating the whole
 * check. useState runs its factory on the server only and hydrates the value.
 *
 * `navigator.connection.saveData` is then consulted as well, which covers the
 * two cases the header cannot: a prerendered page (`nuxt generate` has no
 * request, so the header is never seen) and any client-side navigation.
 */
const saveData = useState('hero-save-data', () =>
  useRequestHeaders(['save-data'])['save-data'] === 'on'
)

/**
 * Animation is opted IN, never opted out. Motion has two orthogonal axes:
 * `is-ready` answers WHETHER MOTION IS ALLOWED AT ALL (mounted, and not
 * Save-Data), while `is-offscreen` answers WHETHER IT IS CURRENTLY RUNNING.
 * `is-ready` remains the single authority for whether motion is allowed.
 *
 * The scene is server-rendered, so its CSS would otherwise start animating
 * during initial paint -- including for visitors with no JavaScript. `is-ready`
 * is the single gate that lets it move, and it is added only from script.
 *
 * Honest note on WCAG 2.2.2 (Pause, Stop, Hide): there is still NO in-page
 * mechanism to stop this motion -- the pause control was removed at the owner's
 * request, and the off-screen suspension below is not a substitute, because the
 * visitor does not control it and scrolling back into view resumes the motion
 * automatically. `prefers-reduced-motion` remains the only real accommodation.
 * That gap is known and accepted; do not let this comment claim otherwise.
 */
const heroEl = ref<HTMLElement | null>(null)
const dataAllowsMotion = ref(false)
const inViewport = ref(true)

/**
 * An IntersectionObserver must never be the sole input to whether motion runs:
 * an earlier draft let it silently re-enable animation for Save-Data visitors
 * when the hero entered the viewport. That is now structurally guaranteed:
 * the observer drives only `is-offscreen` and cannot grant motion.
 */
const ready = computed(() => dataAllowsMotion.value)

let observer: IntersectionObserver | null = null

onMounted(() => {
  // Either signal is enough to suppress motion.
  const clientSaveData = Boolean((navigator as any).connection?.saveData)
  dataAllowsMotion.value = !saveData.value && !clientSaveData

  /**
   * Suspend the scene once it leaves the viewport. 112 animations otherwise keep
   * running for as long as the tab is open, however far down the page the reader
   * has gone.
   *
   * Measured honestly: the main-thread cost is ~1ms of style recalc per 1.6s,
   * i.e. below the noise floor -- this is battery insurance on real hardware,
   * not a fix for a measured regression.
   *
   * This is separate from `is-ready`: toggling `is-ready` off screen removed the
   * animations via `animation: none`, and re-adding a CSS animation restarts it
   * at t=0. Scrolling back therefore replayed the camera push-in and snapped
   * every gear back to its start. Measured before the fix: the camera clock read
   * 633ms on screen, the animation was absent off screen, and on return it read
   * 467ms instead of resuming near 1600ms. Pausing preserves phase.
   */
  if (typeof IntersectionObserver === 'undefined') return
  observer = new IntersectionObserver(
    ([entry]) => {
      if (entry) inViewport.value = entry.isIntersecting
    },
    // Any sliver on screen counts as visible; the scene is full-bleed and a
    // threshold above 0 would stop it while part of it is still showing.
    { threshold: 0 },
  )
  if (heroEl.value) observer.observe(heroEl.value)
})

onUnmounted(() => {
  observer?.disconnect()
  observer = null
})

</script>

<template>
  <section id="top" ref="heroEl" class="net-hero">
    <!-- The stage owns the motion state. The scene inside is a server
         component and cannot receive reactive props, so pause and hydration
         cross the boundary as classes and are picked up by descendant
         selectors in assets/css/hero-scene.css. -->
    <div class="net-hero-media hero-stage" :class="{ 'is-ready': ready, 'is-offscreen': !inViewport }">
      <HeroScene />

      <!-- A vignette, not a flat veil. With white type over pale paper, a
           uniform darkening is what the contrast budget actually depends on;
           the radial component only keeps the edges a touch deeper than the
           centre so the frame reads as lit rather than dimmed. -->
      <div class="net-hero-scrim" aria-hidden="true"></div>
    </div>

    <div class="container net-hero-content">
      <picture>
        <source srcset="/img/logo/mf-kochi-long@2x.webp 2x, /img/logo/mf-kochi-long.webp 1x" type="image/webp" />
        <img
          src="/img/logo/mf-kochi-long.png"
          width="320"
          height="53"
          class="net-hero-logo"
          alt="Maker Faire Kochi"
          decoding="async"
        />
      </picture>

      <h1 class="net-hero-title display-type">
        Every kind of maker.<br />
        <span class="text-outline">Every kind of making.</span>
      </h1>

      <p class="net-hero-subtitle">
        The Greatest Show (&amp; Tell) on Earth comes to Kerala for the very
        first time.
      </p>

      <!-- The date band. This was two `.eyebrow` spans at 12.8px/400 at 0.88
           opacity: the single most important fact on the page, set as its
           smallest text, over moving artwork, and carrying no <time> at all.
           Two <time> elements, because a range is not one instant. -->
      <p class="net-hero-when">
        <span class="net-hero-fact">
          <CalendarDays class="net-hero-fact-icon" :size="18" :stroke-width="2" aria-hidden="true" />
          <time :datetime="EVENT.rangeStart.iso">{{ EVENT.rangeStart.heroLabel }}</time>
          &ndash;
          <time :datetime="EVENT.rangeEnd.iso">{{ EVENT.rangeEnd.heroLabel }}</time>
        </span>
        <span class="net-hero-dot" aria-hidden="true"></span>
        <span class="net-hero-fact">
          <MapPin class="net-hero-fact-icon" :size="18" :stroke-width="2" aria-hidden="true" />
          {{ EVENT.place }}
        </span>
      </p>

      <!-- Interest form (not registration). Primary CTA stays the dark-ground
           neutral "Learn More"; Get Involved is the conversion path. -->
      <div class="net-hero-actions">
        <a href="/interestform" class="btn-maker btn-maker-primary">Get Involved</a>
        <a href="#about" class="btn-maker btn-maker-on-dark">Learn More</a>
      </div>
    </div>
  </section>
</template>

<style scoped>
.net-hero {
  position: relative;
  /* svh, not vh: vh includes the retracted iOS URL bar, which pushes content
     under the browser chrome on first paint. */
  min-height: 100svh;
  display: flex;
  flex-direction: column;
  justify-content: center;
  overflow: hidden;
  background-color: var(--color-ink);
  padding-top: 3rem;
  /* Clearance for the fixed nav rail. */
  padding-bottom: calc(var(--rail-h) + 3rem + env(safe-area-inset-bottom));
}

.net-hero-media {
  position: absolute;
  inset: 0;
  z-index: 0;
}

/* The scene is an <svg> with preserveAspectRatio="xMidYMax slice", which is
   the vector equivalent of object-fit: cover anchored to the ground line --
   so the horizon stays put and the sides crop, rather than the figures
   sliding up and down as the viewport changes. */
.net-hero-media :deep(.hero-scene) {
  position: absolute;
  inset: 0;
  width: 100%;
  height: 100%;
}

.net-hero-scrim {
  position: absolute;
  inset: 0;
  z-index: 3;
  /* Built from --hero-dim in main.css -- that is the single knob. */
  background:
    radial-gradient(
      118% 88% at 50% 46%,
      rgba(0, 0, 0, 0) 0%,
      rgba(0, 0, 0, 0.16) 62%,
      rgba(0, 0, 0, 0.30) 100%
    ),
    rgba(0, 0, 0, var(--hero-dim));
}

/* ── Rhythm, not a uniform stack ──────────────────────────────────────────
   This was `gap: 1.25rem`, which gave six elements — logo, headline, subtitle,
   date band, and two buttons — exactly equal separation. Equal spacing is the
   absence of hierarchy: nothing in the stack said which parts belong together.

   The spacing is graduated instead, so the stack reads as three groups:
   the brand lockup (logo tight to the headline it introduces), the pitch
   (headline + subtitle), and then a real break before the facts and the
   actions, which are what the visitor is here to act on. */
.net-hero-content {
  position: relative;
  z-index: 4;
  display: flex;
  flex-direction: column;
  align-items: center;
  text-align: center;
  gap: 0;
}

/* Was clamp(210px, 24vw, 320px) — a 320px logo directly above an H1 naming the
   same brand, which made the mark compete with the sentence it was introducing.
   It stays (a hero is the one place a logo belongs) but yields the lead. */
.net-hero-logo {
  width: clamp(150px, 17vw, 220px);
  height: auto;
  display: block;
}

.net-hero-title {
  margin-top: var(--sp-3);
  font-size: var(--text-display);
  line-height: var(--text-display-lh);
  /* 22ch, not 18ch: each line is 20-21 characters and must not wrap. */
  max-width: 22ch;
  color: var(--hero-ink);
}

/* The global .text-outline strokes in ink, which vanishes on a dark hero. */
.net-hero-title .text-outline {
  -webkit-text-stroke: 2px var(--hero-ink);
  color: transparent;
}

.net-hero-subtitle {
  margin-top: var(--sp-4);
  max-width: 46ch;
  font-size: clamp(1rem, 1.4vw, 1.2rem);
  color: var(--hero-ink);
  opacity: 0.94;
}

/* A band, not a caption. Solid translucent black rather than a backdrop-filter:
   blurring a 927-element animated SVG behind this is a real per-frame GPU cost,
   and it buys nothing a flat scrim does not already give. Worst-case contrast
   over the dimmed scene measures about 10:1. */
.net-hero-when {
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 0.85rem;
  flex-wrap: wrap;
  /* The break. Everything above is the pitch; everything from here down is
     what the visitor acts on. */
  margin-top: var(--sp-5);
  padding: 0.6rem 1.15rem;
  border-radius: var(--radius-pill);
  background-color: rgba(0, 0, 0, 0.38);
  border: 1px solid rgba(255, 255, 255, 0.22);
  font-family: var(--font-mono);
  font-size: clamp(1rem, 1.7vw, 1.2rem);
  font-weight: 600;
  letter-spacing: 0.02em;
  color: var(--hero-ink);
}

.net-hero-fact {
  display: inline-flex;
  align-items: center;
  gap: 0.45rem;
  white-space: nowrap;
}

.net-hero-fact-icon {
  color: var(--color-cyan);
  flex-shrink: 0;
}

.net-hero-dot {
  width: 4px;
  height: 4px;
  border-radius: 50%;
  background-color: var(--color-cyan);
}

.net-hero-actions {
  display: flex;
  gap: var(--sp-3);
  flex-wrap: wrap;
  justify-content: center;
  margin-top: var(--sp-4);
}

/* Short viewports — a laptop at 200% zoom (1440x900 becomes 720x450), or a phone
   in landscape. The hero is min-height:100svh, so everything inside it has to fit
   in whatever height that is, and the date band is taller than the caption it
   replaced. Tighten the stack rather than let the buttons run under the fixed
   nav rail. */
@media (max-height: 560px) {
  .net-hero {
    padding-top: 1.5rem;
  }

  /* Compress the graduated spacing rather than the content. The stack has to
     fit inside 100svh at 720x450 (a laptop at 200% zoom) without the buttons
     sliding under the fixed rail. */
  .net-hero-title {
    margin-top: var(--sp-1);
  }

  .net-hero-subtitle {
    margin-top: var(--sp-2);
  }

  .net-hero-when {
    margin-top: var(--sp-3);
    padding: 0.45rem 1rem;
  }

  .net-hero-actions {
    margin-top: var(--sp-2);
  }

  .net-hero-logo {
    width: clamp(130px, 14vw, 170px);
  }
}

/* The band stacks rather than wrapping.
   A pill radius on a box that has wrapped to two lines is not a pill — it draws
   a lopsided stadium with the separator dot orphaned at the end of line one.
   Below this width the two facts get a line each, the dot goes away (it
   separates nothing once they are stacked) and the radius drops to a rounded
   rectangle, which is a shape a two-line box can actually hold. */
@media (max-width: 560px) {
  .net-hero-when {
    flex-direction: column;
    gap: 0.4rem;
    border-radius: 18px;
    padding: 0.7rem 1.1rem;
  }

  .net-hero-dot {
    display: none;
  }
}

/* Portrait.
   The old film was a fixed 16:9 raster, so filling a ~9:20 phone meant either
   throwing away three quarters of its width or letterboxing it into a void.
   Neither applied here: the scene is vector and its viewBox can simply be
   cropped. `slice` anchored to xMid/YMax keeps the ground line and the densest
   part of the crowd on screen while the outer zones fall away, so the hero
   stays full-bleed and full-height on a phone with no special case. */
@media (orientation: portrait) and (max-width: 900px) {
  .net-hero-title {
    max-width: 100%;
  }

  .net-hero-actions .btn-maker {
    width: 100%;
    justify-content: center;
  }

}

</style>
